name: simplify
description: Simplify your library.

publish_to: 'none' # Don't publish to pub.dev

# [ App version ] + [ Play store release ID ]
version: 0.0.1+1

# SDK version
environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

# ------------------------------------- - ------------------------------------ #
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
